[target.aarch64-linux-android]
linker = "/nix/store/dz9f94wp9jvrzqbs2a9gmi3a4h04fya1-android-sdk-env/share/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
rustflags = ["-C", "link-arg=--ld-path=mold"]